### ISSUE TITLE
Notes on replacing Jasmine

### ISSUE THREAD

**Issue by Arcanemagus** [wooorm/unified-engine-atom#1]
Since you have a request about it in the readme, you can see where custom test framework support was added to Atom [here](https://github.com/atom/atom/pull/8968), with a Mocha runner implemented [here](https://github.com/binarymuse/atom-mocha-test-runner).

**Comment by wooorm** [comment]
Oh cool! Thanks @Arcanemagus! 💃

**Comment by Arcanemagus** [comment]
Looks like it's been in Atom since v1.2.0.

Also I haven't seen anything about coverage testing, but if you find something I'd be interested to!

**Comment by wooorm** [comment]
👍 I tried using `nyc`, but couldn’t get it to work, as it uses `eval` for some reason, and atom’s security settings don’t allow that... I believe the reason for that, in nyc, was to get a global scope or something, which should probably be fixable with a PR to nyc. Anyway, too much work for now! 😬
